package qydee;

enum TokenType{
    PARENTESIS_DERECHO, PARENTESIS_IZQUIERDO, RESTA, SUMA, DIV, MULTI,
    FUNCION, PUNTO_COMA,
    
    IGUAL, ASIGNACION, 
    EXCL, EXCL_DISTINTO,
    MAYOR, IGUAL_MAYOR, 
    MENOR, IGUAL_MENOR, YY, OO,
    
    INICIO, IDENTIFICADOR, NUMERO,
    
    MATCH, END_MATCH, NOMBRE_F, INPUT, PRINT, RETURN, FOR, IN, WHILE, PUNTOS,
    CADENA,
    COMA, FLECHA, TIPO,
    EOF 
}